version: '3.8'

services:

  db:
    image: postgres:16.3-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventorydb
    networks:
      - inventory

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - inventory



volumes:
  db:

networks:
  inventory:
    driver: bridge